#!/usr/bin/env bash

git clone https://github.com/savq/paq-nvim.git \
    "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/pack/paqs/opt/paq-nvim

# conf
mkdir -p ~/.config/nvim
cp -r ./nvim/init.lua ./nvim/lua ./nvim/after ~/.config/nvim/

# Language servers
yarn global add bash-language-server
yarn global add vscode-css-languageserver-bin
yarn global add vscode-html-languageserver-bin
yarn global add typescript typescript-language-server
yarn global add vim-language-server
# git clone git@github.com:phpactor/phpactor
# cd phpactor
# composer install
# sudo ln -s ./bin/phpactor /usr/local/bin/phpactor
# cd ..

echo "Run 'nvim +PaqInstall' to finish setup"

